# Generated by Django 5.2.7 on 2025-10-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='small_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
