# Generated by Django 5.2.7 on 2025-11-24 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_alter_product_options_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='is_active',
        ),
    ]
