# Generated by Django 5.2.7 on 2025-10-17 18:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0002_product_long_description_product_small_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='threshold',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('motive', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created_user')),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Incomes',
            },
        ),
        migrations.CreateModel(
            name='Offert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('init_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerts', to='products.product')),
            ],
            options={
                'verbose_name': 'Offert',
                'verbose_name_plural': 'Offerts',
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('motive', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created_user')),
            ],
            options={
                'verbose_name': 'Spent',
                'verbose_name_plural': 'Spents',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_operation', models.CharField(choices=[('1', 'salida'), ('2', 'entrada')], default='2', max_length=1)),
                ('action_type', models.CharField(choices=[('1', 'simple'), ('2', 'multiple')], default='1', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('motive', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('cant', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stock_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_one_movement', to='inventory.stock')),
                ('stock_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_two_movement', to='inventory.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stock_movement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock movement',
                'verbose_name_plural': 'Stocks Movements',
            },
        ),
    ]
