# Generated by Django 5.2.7 on 2025-10-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stock_threshold_income_offert_outcome_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Offert',
        ),
    ]
