# Generated by Django 5.2.7 on 2025-10-20 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_expire_date_delete_offert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='created_user',
        ),
        migrations.RenameField(
            model_name='stockmovement',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='stock_one',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='stock_two',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='create_by_user_full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='create_by_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_from_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_from_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_from_new_cant',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_from_prev_cant',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_from_product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_from_product_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_from_wharehouse_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_from_wharehouse_name',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_to_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_to_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_to_new_cant',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_to_prev_cant',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_to_product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_to_product_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_to_wharehouse_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_to_wharehouse_name',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cant',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='motive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Outcome',
        ),
    ]
