# Generated by Django 5.2.7 on 2025-11-18 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_outcome_created_user_and_more'),
        ('products', '0005_category_alter_product_options_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='user',
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_stocks', to='products.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_stocks', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='inventory.store'),
        ),
    ]
