# Generated by Django 5.2.7 on 2025-11-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_stockmovement_user_alter_stock_product_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cant',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
